## Custom configuration

#server:
#  address: 192.168.1.2

cortex:
  # hosts file must map emotivcortex.com to 91.165.202.208
  cortexServerAddress: emotivcortex.com:1111
  headsetIdsToCodes:
    EPOCPLUS-4A2C065F: E1
    EPOCPLUS-4A2C0686: E2
  useSsl: true
  # Provide Emotiv credentials via command line
#  emotiv:
#    username:
#    password:
#    clientId:
#    clientSecret:

grpc:
  port: 9991
  #masterLookupIntervalMillis: 5000
  masterSyncIntervalMillis: 1000

## Standard Bootique configuration

jdbc:
  octopus:
    url: jdbc:postgresql://localhost:5432/octopus?currentSchema=octopus
    maxActive: 2
    username: postgres
    password: postgres

log:
  level: warn
  loggers:
    net.manaty:
      level: trace
  appenders:
    - type: console
      logFormat: '[%d{dd/MMM/yyyy:HH:mm:ss}] %t %-5p %c{1}: %m%n'